# 시각화 멘토링 2주차 과제 김영은

## NUMPY

### 1. 0부터 8까지의 숫자를 가지고 있는 3행 3열의 행렬을 제작해 주세요

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [61]:
a = np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 2. 랜덤으로 3개의 정수를 가지고 있는 행렬을 만들어 주세요

In [66]:
np.random.randint(1,100,3)

array([66, 70, 22])

### 3. A = 3x3, B = 3x4 형태를 가진 임의의 행렬을 만들어 두개의 곱을 실현한 후, 그것의 역행렬이 존재하는지 확인해 주세요

In [82]:
A = np.random.rand(3,3) ;A

array([[0.54797245, 0.24911391, 0.61907526],
       [0.19191718, 0.24481386, 0.08368051],
       [0.42151587, 0.21918338, 0.57082359]])

In [83]:
B = np.random.rand(3,4) ;B

array([[0.43271155, 0.63081674, 0.14039821, 0.79559084],
       [0.78480896, 0.96599698, 0.33608169, 0.23481531],
       [0.65832474, 0.71570215, 0.24745527, 0.2892777 ]])

In [87]:
C = np.matmul(A, B)
C

array([[0.8401734 , 1.02938698, 0.31385041, 0.67354229],
       [0.33026584, 0.41744435, 0.12992947, 0.2343805 ],
       [0.73019916, 0.88616943, 0.2740969 , 0.55194832]])

In [90]:
C @ np.linalg.inv(C) #역행렬 존재 X

LinAlgError: Last 2 dimensions of the array must be square

### 4. 2019년 7월 서울 평균기온 데이터는 다음과 같습니다

temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])
         
### 7월 의 평균 기온은 몇도입니까?

In [79]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])
temp

array([23.9, 24.4, 24.1, 25.4, 27.6, 29.7, 26.7, 25.1, 25. , 22.7, 21.9,
       23.6, 24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 28.6, 28. , 25.1, 26.7,
       28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [80]:
temp.mean()

25.90322580645161

### 5. 26.5도 이상을 기록할경우 폭염 주의보를 발령하려 합니다. 폭염주의보를 기록한 날짜는 몇 일 입니까?

In [94]:
sum(temp >= 26.5)

12

### 6. 데이터를 화씨로 변환하려 합니다. 주어진 공식을 활용하여 7월 데이터를 화씨로 변환해  주세요

In [96]:
####  화씨 = 섭씨 * 1.8 +32
temp_new = temp * 1.8 + 32
temp_new

array([75.02, 75.92, 75.38, 77.72, 81.68, 85.46, 80.06, 77.18, 77.  ,
       72.86, 71.42, 74.48, 76.82, 78.62, 74.84, 76.46, 78.08, 80.42,
       83.48, 82.4 , 77.18, 80.06, 82.58, 79.7 , 79.34, 78.62, 83.12,
       78.98, 81.5 , 82.58, 78.44])

### 7. 7월 1일은 월요일이었습니다. 매주 화,목,토요일 폭염주의보가 발령되는 경우 아이스크림 나눔 행사를 진행하려고 합니다. 7월동안 아이스크림 행사가 진행된 횟수는 몇번일까요?

In [113]:
zero = np.zeros(4)
temp_event = np.append(temp,zero).reshape(5, 7) ; temp_event

array([[23.9, 24.4, 24.1, 25.4, 27.6, 29.7, 26.7],
       [25.1, 25. , 22.7, 21.9, 23.6, 24.9, 25.9],
       [23.8, 24.7, 25.6, 26.9, 28.6, 28. , 25.1],
       [26.7, 28.1, 26.5, 26.3, 25.9, 28.4, 26.1],
       [27.5, 28.1, 25.8,  0. ,  0. ,  0. ,  0. ]])

In [116]:
temp_event[:,[1,3,5]] #화목토

array([[24.4, 25.4, 29.7],
       [25. , 21.9, 24.9],
       [24.7, 26.9, 28. ],
       [28.1, 26.3, 28.4],
       [28.1,  0. ,  0. ]])

In [125]:
np.sum(temp_event[:,[1,3,5]] >=26.5)

6

### 8.  7월 15일까지를 전반, 16일~31일을 후반으로 하여 더위의 변화를 확인하려 합니다. 전, 후반 각각의 평균은 얼마인가요?

In [132]:
temp

array([23.9, 24.4, 24.1, 25.4, 27.6, 29.7, 26.7, 25.1, 25. , 22.7, 21.9,
       23.6, 24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 28.6, 28. , 25.1, 26.7,
       28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [129]:
temp_1 = temp[:15] ; temp_1

array([23.9, 24.4, 24.1, 25.4, 27.6, 29.7, 26.7, 25.1, 25. , 22.7, 21.9,
       23.6, 24.9, 25.9, 23.8])

In [133]:
temp_2 = temp[15:] ; temp_2

array([24.7, 25.6, 26.9, 28.6, 28. , 25.1, 26.7, 28.1, 26.5, 26.3, 25.9,
       28.4, 26.1, 27.5, 28.1, 25.8])

In [135]:
print("전반 평균 기온 : {}, 후반 평균 기온 : {} :".format(temp_1.mean(),temp_2.mean()))

전반 평균 기온 : 24.979999999999997, 후반 평균 기온 : 26.76875 :


### 9. 8월을 관측했더니 매일 정확히 2도씩 상승했습니다. 7월 데이터를 활용해 8월 데이터를 만들어 주세요

In [136]:
temp_8 = temp + 2

In [138]:
temp_8

array([25.9, 26.4, 26.1, 27.4, 29.6, 31.7, 28.7, 27.1, 27. , 24.7, 23.9,
       25.6, 26.9, 27.9, 25.8, 26.7, 27.6, 28.9, 30.6, 30. , 27.1, 28.7,
       30.1, 28.5, 28.3, 27.9, 30.4, 28.1, 29.5, 30.1, 27.8])

## PANDAS

### 연습문제 2

In [2]:
import pandas as pd
import numpy as np

In [46]:
table_data2 = {'연도': [2019, 2019, 2019, 2020, 2020,2020,2020,2021,2021],
                '국가': ['한국', '미국', '중국', '한국','미국','중국','일본','한국','미국'],
                '지수': [200, 250, 450, 300, 370,420,381,370,410],
              '지수2':[2.1, 3.2, 3.8, 2.6, 3.4, 4.0, 2.4, 3.3, 3.8]}

exc2 = pd.DataFrame(table_data2)
exc2

연도  국가   지수  지수2
0  2019  한국  200  2.1
1  2019  미국  250  3.2
2  2019  중국  450  3.8
3  2020  한국  300  2.6
4  2020  미국  370  3.4
5  2020  중국  420  4.0
6  2020  일본  381  2.4
7  2021  한국  370  3.3
8  2021  미국  410  3.8

### 1.   지수, 지수2의 평균과 표준편차를 확인하려면?

In [28]:
a = exc2.describe();a

연도          지수       지수2
count     9.000000    9.000000  9.000000
mean   2019.888889  350.111111  3.177778
std       0.781736   83.112040  0.672268
min    2019.000000  200.000000  2.100000
25%    2019.000000  300.000000  2.600000
50%    2020.000000  370.000000  3.300000
75%    2020.000000  410.000000  3.800000
max    2021.000000  450.000000  4.000000

In [29]:
a.iloc[[1,2],[1,2]]

지수       지수2
mean  350.111111  3.177778
std    83.112040  0.672268

### 2. "국가"열을 시리즈 형태로 출력하려면?

In [32]:
exc2['국가']

0    한국
1    미국
2    중국
3    한국
4    미국
5    중국
6    일본
7    한국
8    미국
Name: 국가, dtype: object

### 3. "국가","지수2" 열을 한번에 출력하려면?

In [33]:
exc2[['국가','지수2']]

국가  지수2
0  한국  2.1
1  미국  3.2
2  중국  3.8
3  한국  2.6
4  미국  3.4
5  중국  4.0
6  일본  2.4
7  한국  3.3
8  미국  3.8

### 4. 연도가 2020, 2021년이고 국가가 미국인 데이터를 추출하려면?

In [35]:
exc2.query('연도 in [2020, 2021] & 국가 == "미국"')


연도  국가   지수  지수2
4  2020  미국  370  3.4
8  2021  미국  410  3.8

### 5. 사용한 데이터(exc2)를 csv파일 형태로 저장하려면?

In [44]:
%pwd
exc2.to_csv('exc2.csv', index = False)

### 6. 사용한 데이터(exc2)를 불러오려면?

In [45]:
df=pd.read_csv('exc2.csv', encoding='utf-8');df

연도  국가   지수  지수2
0  2019  한국  200  2.1
1  2019  미국  250  3.2
2  2019  중국  450  3.8
3  2020  한국  300  2.6
4  2020  미국  370  3.4
5  2020  중국  420  4.0
6  2020  일본  381  2.4
7  2021  한국  370  3.3
8  2021  미국  410  3.8